name: Build and Deploy
on:
  push:
    branches:
      - main
      - master
permissions:
  contents: write
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v6
      with:
        persist-credentials: false
    - name: Package static site
      run: |
        mkdir -p __site
        cp index.html __site/
        cp 404.html __site/
        cp site.css __site/
        cp -r assets __site/assets
        cp -r contact __site/contact
        cp -r cv __site/cv
        cp -r publications __site/publications
        cp -r software __site/software
        cp -r achievements __site/achievements
        cp -r notes __site/notes
    - name: Build and Deploy
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages
        folder: __site
